### ISSUE TITLE
Draw a character at a specific position

### ISSUE THREAD

**Issue by Bonemind** [r00ster91/lime#1]
First off, cool shard, I've been looking for something similar so this should save me time, thanks!

On to the question, I might be missing something but I don't see if i could draw a character to a certain position (e.g. "a" to row 5, col 7). Is this possible?

Cheers

**Comment by r00ster91** [comment]
Thank you for your interest!
Yes that's possible with `Lime.print`:
```crystal
Lime.print('a', 7, 5) # Inserts the char into the buffer
Lime.draw # Draws the buffer
```
You might be interested in the docs for all the methods that you can use on `Lime`: https://r00ster91.github.io/lime/Lime.html.
